[profile.default]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
src = "src"
test = "test"
libs = ["lib"]
evm_version = "paris"
ffi = false

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink-brownie-contracts/"
]



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
